[project]
name = "package-dev-utils"
version = "0.1.6"
description = "Common development utilities for Python packages"
authors = [{name = "Quinten Roets", email = "qdr2104@columbia.edu"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
<<<<<<< HEAD
    "hypothesis >=6.91.0, <7",
    "package-dev-tools >=0.5.11, <1",
=======
    "package-dev-tools >=0.7.0, <1",
    "package-dev-utils >=0.1.6, <1",
>>>>>>> template
]

[project.urls]
"Source Code" = "https://github.com/quintenroets/package-dev-utils"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
command_line = "-m pytest tests"

[tool.coverage.report]
precision = 4
fail_under = 100

[tool.mypy]
strict = true
no_implicit_reexport = false

[tool.pytest.ini_options]
pythonpath = [
    "src", ".",
]

[tool.ruff]
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",   # annotated with Any
    "D",        # docstrings
    "G004",     # logging f-string
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401"  # unused import
]
"tests/*" = [
    "S101"  # assert used
]

[tool.setuptools.package-data]
package_dev_utils = ["py.typed"]
